name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  nix:
    name: build in nix
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - name: build
        run: |
          set -x
          ./show-source-info.sh
